%YAML:1.0
---
Camera:
  Width: 0               # 图像宽度 (0=相机最大值, 需为2或4的倍数)
  Height: 0              # 图像高度 (0=相机最大值, 需为2或4的倍数)
  ExposureTime: 1000.0   # 曝光时间 (us)
  Gain: 10.0             # 增益
  Gamma: 0.8             # Gamma
  TriggerMode: 0         # 0: Continuous, 1: External
